layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:

  - name: C
    web_url: https://github.com/topics/c
    image_url: https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg

 - name: C++
    web_url: https://github.com/topics/cplusplus
    image_url: https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg

 - name: C#
    web_url: https://github.com/topics/csharp
    image_url: https://raw.githubusercontent.com/devicons/devicon/master/icons/csharp/csharp-original.svg

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

 - name: Bootstrap
    web_url: https://github.com/topics/bootstrap
    image_url: https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg

 - name: git
    web_url: https://github.com/topics/git
    image_url: https://camo.githubusercontent.com/fbfcb9e3dc648adc93bef37c718db16c52f617ad055a26de6dc3c21865c3321d/68747470733a2f2f7777772e766563746f726c6f676f2e7a6f6e652f6c6f676f732f6769742d73636d2f6769742d73636d2d69636f6e2e737667

 - name: java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg


  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg
